requires:
  "@ai-policies/core": "^1.0.0"
  "@ai-policies/frontend-react": "^1.0.0"

output:
  cursor: ./.cursorrules
  copilot: ./.copilot/instructions.md

compose:
  order: [core, domain, stack, team]
  protectedLayers: [core]
  teamAppend: true

overrides:
  teamAppendContent: |
    ## Team-Specific React Guidelines

    ### Component Library
    - Use Material-UI components when available
    - Follow the company design system specifications
    - Prefer composition over complex prop interfaces

    ### State Management
    - Use React Query for server state
    - Use Zustand for complex client state
    - Keep component state local when possible

    ### Testing
    - Write integration tests for user flows
    - Use React Testing Library for component tests
    - Mock external API calls in tests
