source 'https://rubygems.org'
ruby '3.2.0'

gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'pg', '~> 1.4'
gem 'sequel', '~> 5.68'
gem 'redis', '~> 5.0'
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.7'
gem 'rack-cors', '~> 2.0'
gem 'dotenv', '~> 2.8'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.20'
end
