import type { CompositionResult } from '@ai-policies/core-schemas';

export interface CopilotRenderOptions {
  includeSafetyConstraints?: boolean;
  includePromptTemplates?: boolean;
  includeCodeExamples?: boolean;
}

/**
 * Render Copilot instructions from composition result
 */
export function renderCopilotInstructions(
  result: CompositionResult,
  options: CopilotRenderOptions = {}
): string {
  let output = '# GitHub Copilot Instructions\n\n';
  output +=
    'This document provides guidelines and instructions for GitHub Copilot ';
  output +=
    'to assist with code generation and suggestions in this project.\n\n';

  // Add main content
  output += result.content;

  // Add safety constraints section if requested
  if (options.includeSafetyConstraints) {
    output += '\n\n## Safety Constraints\n\n';
    output += '### Data Protection\n';
    output +=
      '- 🚫 **Never** include real API keys, passwords, or secrets in code\n';
    output += '- 🚫 **Never** log sensitive user information\n';
    output += '- ✅ **Always** validate and sanitize user input\n';
    output += '- ✅ **Always** use environment variables for configuration\n';
  }

  // Add prompt templates if requested
  if (options.includePromptTemplates) {
    output += '\n\n## Prompt Templates\n\n';
    output += '### Code Generation Request\n';
    output += 'When generating code, please:\n';
    output += '1. Follow the established patterns in this codebase\n';
    output += '2. Include appropriate error handling\n';
    output += '3. Add relevant comments for complex logic\n';
    output += '4. Ensure security best practices are followed\n';
  }

  // Add attribution footer
  const packageList = Object.entries(result.metadata.packages)
    .map(([name, version]) => `- ${name}@${version}`)
    .join('\n');

  output += '\n\n---\n\n';
  output += '## Document Information\n\n';
  output += '**Generated by**: AI Policies\n';
  output += `**Content hash**: \`${result.metadata.contentHash}\`\n\n`;
  output += '### Policy Packages Used\n';
  output += packageList;
  output +=
    '\n\n> This file is automatically generated. To modify these instructions, ';
  output += 'update your policy packages and run `ai-policies sync`.';

  return output;
}

/**
 * Validate Copilot instructions content
 */
export function validateCopilotInstructions(content: string): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Check for minimum content
  if (content.length < 100) {
    errors.push('Content is too short for meaningful instructions');
  }

  // Check for proper structure
  if (!content.includes('#')) {
    errors.push('Missing headers - consider adding section headers');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

export class CopilotProvider {
  render(
    result: CompositionResult,
    options: CopilotRenderOptions = {}
  ): string {
    return renderCopilotInstructions(result, options);
  }

  validate(content: string): { valid: boolean; errors: string[] } {
    return validateCopilotInstructions(content);
  }
}
