name: 'AI Policies Update Bot'
description: 'Automatically update AI Policies configurations across repositories'
author: 'AI Policies Team'

branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token with repo access'
    required: true

  repositories:
    description: 'Comma-separated list of repositories to update (owner/repo format)'
    required: false
    default: ''

  organization:
    description: 'GitHub organization to search for repositories with AI Policies'
    required: false
    default: ''

  branch-name:
    description: 'Name for the update branch'
    required: false
    default: 'ai-policies/auto-update'

  commit-message:
    description: 'Commit message template'
    required: false
    default: 'chore: update AI Policies configurations'

  pr-title:
    description: 'Pull request title template'
    required: false
    default: 'chore: update AI Policies configurations'

  pr-body:
    description: 'Pull request body template'
    required: false
    default: |
      ## 🤖 Automated AI Policies Update

      This pull request was automatically generated to update your AI Policies configurations.

      ### Changes
      - Updated policy packages to latest versions
      - Regenerated IDE configuration files

      ### Review Required
      Please review the changes to ensure they align with your team's preferences.

      ---
      *Generated by [AI Policies Update Bot](https://github.com/ai-policies/ai-policies)*

  auto-merge:
    description: 'Whether to enable auto-merge on created PRs'
    required: false
    default: 'false'

  reviewers:
    description: 'Comma-separated list of GitHub usernames to request reviews from'
    required: false
    default: ''

  team-reviewers:
    description: 'Comma-separated list of GitHub team names to request reviews from'
    required: false
    default: ''

  labels:
    description: 'Comma-separated list of labels to add to the PR'
    required: false
    default: 'dependencies,ai-policies,automated'

  dry-run:
    description: 'Run in dry-run mode (no actual changes)'
    required: false
    default: 'false'

outputs:
  repositories-updated:
    description: 'Number of repositories that were updated'

  pull-requests-created:
    description: 'URLs of pull requests that were created'

  repositories-skipped:
    description: 'List of repositories that were skipped (no changes needed)'

  errors:
    description: 'List of repositories that encountered errors'

runs:
  using: 'node20'
  main: 'dist/index.js'
