import type { CompositionResult } from '@ai-policies/core-schemas';

export interface CursorRenderOptions {
  includeCategories?: boolean;
  includeAttribution?: boolean;
}

/**
 * Render Cursor rules from composition result
 */
export function renderCursorRules(
  result: CompositionResult,
  options: CursorRenderOptions = {}
): string {
  let output = result.content;

  // Add attribution footer if requested
  if (options.includeAttribution) {
    const packageList = Object.entries(result.metadata.packages)
      .map(([name, version]) => `- ${name}@${version}`)
      .join('\n');

    output += '\n\n---\n\n';
    output += '## Generated by AI Policies\n\n';
    output +=
      'This file was automatically generated from the following policy packages:\n\n';
    output += packageList;
    output +=
      '\n\n> Do not edit this file directly. Use `ai-policies sync` to regenerate.';
  }

  return output;
}

/**
 * Validate Cursor rules content
 */
export function validateCursorRules(content: string): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Check for minimum content
  if (content.length < 50) {
    errors.push('Content is too short for meaningful rules');
  }

  // Check for proper structure
  if (!content.includes('#')) {
    errors.push('Missing headers - consider adding section headers');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

export class CursorProvider {
  render(result: CompositionResult, options: CursorRenderOptions = {}): string {
    return renderCursorRules(result, options);
  }

  validate(content: string): { valid: boolean; errors: string[] } {
    return validateCursorRules(content);
  }
}
